// <auto-generated />
using System;
using GuestManagementService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuestManagementService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GuestManagementServiceDbContext))]
    [Migration("20260815023630_AddInvitationTemplateSnapshotAndPublicLink")]
    partial class AddInvitationTemplateSnapshotAndPublicLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuestManagementService.Domain.EventReferences.EventReference", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<TimeOnly?>("EventStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("event_start_time");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<string>("VenueAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("venue_address");

                    b.Property<string>("VenueName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue_name");

                    b.Property<string>("VenueNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("venue_notes");

                    b.HasKey("EventId")
                        .HasName("pk_event_references");

                    b.ToTable("event_references", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Domain.Guests.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NotSent")
                        .HasColumnName("delivery_status");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_address");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)")
                        .HasColumnName("invitation_token");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NormalizedEmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email_address");

                    b.Property<string>("NormalizedPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("normalized_phone_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("RsvpStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NoResponse")
                        .HasColumnName("rsvp_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guests");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_guests_event_id");

                    b.HasIndex("InvitationToken")
                        .IsUnique()
                        .HasDatabaseName("ix_guests_invitation_token");

                    b.HasIndex("EventId", "NormalizedEmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_guests_event_id_normalized_email_address")
                        .HasFilter("normalized_email_address IS NOT NULL");

                    b.HasIndex("EventId", "NormalizedPhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_guests_event_id_normalized_phone_number");

                    b.HasIndex("TenantId", "EventId")
                        .HasDatabaseName("ix_guests_tenant_id_event_id");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Domain.Invitations.EventInvitationSettings", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CssContent")
                        .HasColumnType("text")
                        .HasColumnName("css_content");

                    b.Property<string>("FieldValues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_values");

                    b.Property<string>("HtmlContent")
                        .HasColumnType("text")
                        .HasColumnName("html_content");

                    b.Property<string>("JsContent")
                        .HasColumnType("text")
                        .HasColumnName("js_content");

                    b.Property<DateTimeOffset?>("PreviewExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("preview_expires_at");

                    b.Property<string>("PreviewToken")
                        .HasColumnType("text")
                        .HasColumnName("preview_token");

                    b.Property<string>("PublicEventToken")
                        .HasColumnType("text")
                        .HasColumnName("public_event_token");

                    b.Property<bool>("PublicLinkEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("public_link_enabled");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<int?>("TemplateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("template_version");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("EventId")
                        .HasName("pk_event_invitation_settings");

                    b.HasIndex("PreviewToken")
                        .IsUnique()
                        .HasDatabaseName("ix_event_invitation_settings_preview_token");

                    b.HasIndex("PublicEventToken")
                        .IsUnique()
                        .HasDatabaseName("ix_event_invitation_settings_public_event_token");

                    b.ToTable("event_invitation_settings", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Infrastructure.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<int>("HandleAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("handle_attempts");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
