// <auto-generated />
using System;
using GuestManagementService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuestManagementService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GuestManagementServiceDbContext))]
    [Migration("20260711045218_AddSeatAssignments")]
    partial class AddSeatAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuestManagementService.Domain.EventReferences.EventReference", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("EventId")
                        .HasName("pk_event_references");

                    b.ToTable("event_references", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Domain.Guests.Guest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email_address");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("NormalizedEmailAddress")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email_address");

                    b.Property<string>("NormalizedPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("normalized_phone_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_guests");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_guests_event_id");

                    b.HasIndex("EventId", "NormalizedEmailAddress")
                        .IsUnique()
                        .HasDatabaseName("ux_guests_event_id_normalized_email_address")
                        .HasFilter("normalized_email_address IS NOT NULL");

                    b.HasIndex("EventId", "NormalizedPhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_guests_event_id_normalized_phone_number");

                    b.HasIndex("TenantId", "EventId")
                        .HasDatabaseName("ix_guests_tenant_id_event_id");

                    b.ToTable("guests", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Domain.Seating.SeatAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GuestId")
                        .HasColumnType("uuid")
                        .HasColumnName("guest_id");

                    b.Property<int>("SeatIndex")
                        .HasColumnType("integer")
                        .HasColumnName("seat_index");

                    b.Property<Guid>("SeatingLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("seating_layout_id");

                    b.Property<Guid>("SeatingTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("seating_table_id");

                    b.HasKey("Id")
                        .HasName("pk_seat_assignments");

                    b.HasIndex("GuestId");

                    b.HasIndex("SeatingLayoutId", "GuestId")
                        .IsUnique()
                        .HasDatabaseName("ux_seat_assignments_layout_id_guest_id");

                    b.HasIndex("SeatingTableId", "SeatIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_seat_assignments_table_id_seat_index");

                    b.ToTable("seat_assignments", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Domain.Seating.SeatingLayout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seating_layouts");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_seating_layouts_event_id");

                    b.HasIndex("TenantId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("ux_seating_layouts_tenant_id_event_id");

                    b.ToTable("seating_layouts", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Domain.Seating.SeatingTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsFull")
                        .HasColumnType("boolean")
                        .HasColumnName("is_full");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<double?>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double?>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<double>("Rotation")
                        .HasColumnType("double precision")
                        .HasColumnName("rotation");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer")
                        .HasColumnName("seat_count");

                    b.Property<Guid>("SeatingLayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("seating_layout_id");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("shape");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seating_tables");

                    b.HasIndex("SeatingLayoutId")
                        .HasDatabaseName("ix_seating_tables_seating_layout_id");

                    b.ToTable("seating_tables", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Infrastructure.Persistence.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("event_type");

                    b.Property<int>("HandleAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("handle_attempts");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("GuestManagementService.Domain.Seating.SeatAssignment", b =>
                {
                    b.HasOne("GuestManagementService.Domain.Guests.Guest", null)
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seat_assignments_guest_id");

                    b.HasOne("GuestManagementService.Domain.Seating.SeatingLayout", null)
                        .WithMany("Assignments")
                        .HasForeignKey("SeatingLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seat_assignments_seating_layout_id");

                    b.HasOne("GuestManagementService.Domain.Seating.SeatingTable", null)
                        .WithMany()
                        .HasForeignKey("SeatingTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seat_assignments_seating_table_id");
                });

            modelBuilder.Entity("GuestManagementService.Domain.Seating.SeatingTable", b =>
                {
                    b.HasOne("GuestManagementService.Domain.Seating.SeatingLayout", null)
                        .WithMany("Tables")
                        .HasForeignKey("SeatingLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_seating_tables_seating_layout_id");
                });

            modelBuilder.Entity("GuestManagementService.Domain.Seating.SeatingLayout", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Tables");
                });
#pragma warning restore 612, 618
        }
    }
}
