@GuestManagementService.Api_HostAddress = http://localhost:5000

GET {{GuestManagementService.Api_HostAddress}}/ping
Accept: application/json

###

POST {{GuestManagementService.Api_HostAddress}}/guest
Content-Type: application/json

{
  "eventId": "00000000-0000-0000-0000-000000000000",
  "guestInfo": {
    "firstName": "Ada",
    "lastName": "Lovelace",
    "phoneNumber": "+15551234567",
    "emailAddress": "ada@example.com",
    "gender": "preferNotToSay"
  }
}

###

POST {{GuestManagementService.Api_HostAddress}}/guests/query
Content-Type: application/json

{
  "eventId": "00000000-0000-0000-0000-000000000000",
  "pageNumber": 1,
  "pageSize": 20,
  "search": "ada",
  "sortBy": "name",
  "sortDirection": "asc"
}

###
